### ISSUE TITLE
Inference on own dataset

### ISSUE THREAD

**Issue by jroessler** [Gal4way/TPD#10]
Is it possible to run the model on my own dataset? If so, how? Thank you!

**Comment by KIRAN-MK-211** [comment]
You have to prepare the dataset in the format of VITON HD. Follow this file: `[https://github.com/sangyun884/HR-VITON/blob/main/Preprocessing.md](https://github.com/sangyun884/HR-VITON/blob/main/Preprocessing.md) ` to prepare the dataset.
