### ISSUE TITLE
Problem in Config files in inference.py and tensor mismatch in ddim.py

### ISSUE THREAD

**Issue by han023** [Gal4way/TPD#14]
First I got an error with the conda environment because the default command to create the environment was not running successfully because of version issues. I made the environment manually and downloaded all the libraries. Then a second error was raised in the taming library that you download directly from GitHub. It is not downloading in any case. I tried a different solution but finally, I installed it manually. 

As you've given instructions to run the Inference code, I ran the code. I got an error that there was no IDM found so I changed the path to my current path error was solved after I reran the code but I got an error on line 256 in inference.py
`PermissionError: [Errno 13] Permission denied: 'D:\\texture based paper repo'`
```
    parser.add_argument(
        "--config",
        type=str,
        default="",
        help="path to config which constructs model",
    )
```
I tried many solutions but got  success when I specified the default path of the inference_VITONHD_paired.yml file like this 
```
    parser.add_argument(
        "--config",
        type=str,
        default="d:\\texture based paper repo\\configs\\inference\\inference_VITONHD_paired.yaml",
        help="path to config which constructs model",
    ) 
```

**_Is this change correct or not?_** 

and there are 2 folders in the config folder inference and train and they have a total of 3 yaml files so if I follow the upper solution can I do for all three files and run the inference code?

after this change, I ran the code the code started running but got another error that is a tensor mismatch the error is coming on ddim.py on line number 176 

```
x=[torch.cat](http://torch.cat/)([x,kwargs['inpaint_image'],kwargs['inpaint_mask'],kwargs['posemap'],kwargs['densepose']],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 64 but got size 96 for tensor number 1 in the list.
```

_**This error is causing me to change the code. if I change the code can it produce the desired output or not? If not then please help me to solve the error or you solve this and update on GitHub? I have tried changing the code but got an error so please give me a solution. What should I do to run the code?**_

This is the final error that I got after removing the tensor error.

```
return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Given groups=1, weight of size [320, 18, 3, 3], expected input[5, 20, 64, 64] to have 18 channels, but got 20 channels instead
```

**Comment by Gal4way** [comment]
Could u present you inference command here, i need to check this first.

**Comment by han023** [comment]
Well I am running code directly from vs code I open the inference.py file and run it

inference.sh file is 
```
# VITONHD_release_input_person_combine_garment_240epochs_paired
CUDA_VISIBLE_DEVICES=0 python scripts/inference.py \
--config configs/inference/inference_VITONHD_paired.yaml \
--ckpt checkpoints/release/TPD_240epochs.ckpt \
--outdir inference_logs/VITONHD/VITONHD_release_input_person_combine_garment_240epochs_paired/ \
--seed 321 \
--batch_size 15 \
--predicted_mask_dilation 0 \
--C 5 \
--H 512 \
--W 768 \


# VITONHD_release_input_person_combine_garment_240epochs_unpaired
CUDA_VISIBLE_DEVICES=1 python scripts/inference.py \
--config configs/inference/inference_VITONHD_unpaired.yaml \
--ckpt checkpoints/release/TPD_240epochs.ckpt \
--outdir inference_logs/VITONHD/VITONHD_release_input_person_combine_garment_240epochs_unpaired/ \
--seed 321 \
--batch_size 15 \
--C 5 \
--H 512 \
--W 768 \
```

**Comment by Gal4way** [comment]
PermissionError: [Errno 13] Permission denied: 'D:\\texture based paper repo'

This error is likely due to permission issues. Although you resolved it by specifying the default path, I still recommend checking to ensure that the config file is loaded correctly.

x=[torch.cat](http://torch.cat/)([x,kwargs['inpaint_image'],kwargs['inpaint_mask'],kwargs['posemap'],kwargs['densepose']],dim=1)
RuntimeError: Sizes of tensors must match except in dimension 1. Expected size 64 but got size 96 for tensor number 1 in the list.

The error indicates that the shape of your initialization for  x does not match the shape requirements of conditions such as `inpaint_image`. I suggest you debug the shape of  x to check if there's an issue with the initialization. I can assure you that my original code can run without any modifications. As long as you follow the process outlined in the README precisely, everything should work as expected. 

Good luck!

**Comment by han023** [comment]
thank you code has been run after a lot of tries 

I am not passing arguments when running code from vs code
