### ISSUE TITLE
The effect on the lower body was not very good

### ISSUE THREAD

**Issue by RayTang88** [Gal4way/TPD#15]
Thank you for your wonderful work .

I tested the code and the result was good on the garment of upper body , but the result on the lower body was not very good. The result was very strange. If I want to have a good dressing effect on shorts, pants, dresses, and skirts, where should I modify in the code? Or what should be done, do you have any good suggestions?

**Comment by Gal4way** [comment]
Hi! Thank you for your feedback. The released checkpoint was pretrained on the VITON-HD dataset, which primarily includes images of upper clothing. This limitation might affect performance when generating other types of garments. To achieve better results with different garment types, such as dresses, you would need to train the model on datasets specifically containing those garments, like DressCode. You can have a try.

**Comment by RayTang88** [comment]
OK, thanks for your suggestion, I'll try it now.

**Comment by codestella** [comment]
@RayTang88 did you get some result? I am facing the same issue.

**Comment by codestella** [comment]
@RayTang88 could you share the code? I want to help you to improve the effect.
my email address is howtowhy@gmail.com
