### ISSUE TITLE
The model cannot be loaded using the config file in the inference.sh......

### ISSUE THREAD

**Issue by xdfeng07** [Gal4way/TPD#2]
when i was running the code, the message below appeared:

RuntimeError: Error(s) in loading state_dict for LatentDiffusion:
	size mismatch for model.diffusion_model.input_blocks.0.0.weight: copying a param with shape torch.Size([320, 27, 3, 3]) from checkpoint, the shape in current model is torch.Size([320, 18, 3, 3]).
	size mismatch for model.diffusion_model.out.2.weight: copying a param with shape torch.Size([6, 320, 3, 3]) from checkpoint, the shape in current model is torch.Size([5, 320, 3, 3]).
	size mismatch for model.diffusion_model.out.2.bias: copying a param with shape torch.Size([6]) from checkpoint, the shape in current model is torch.Size([5]).

**Comment by Gal4way** [comment]
Hi, it seems like there is something wrong with the uploaded ckpt. We have uploaded a new ckpt, and the new one runs fine on my pc. Please download the new ckpt and try again.

**Comment by xdfeng07** [comment]
> Hi, it seems like there is something wrong with the uploaded ckpt. We have uploaded a new ckpt, and the new one runs fine on my pc. Please download the new ckpt and try again.

thank you so much!

**Comment by xdfeng07** [comment]
> Hi, it seems like there is something wrong with the uploaded ckpt. We have uploaded a new ckpt, and the new one runs fine on my pc. Please download the new ckpt and try again.

i have tried the new model, and everything is quite OK, thanks again so much!
