### ISSUE TITLE
 Online experience effect

### ISSUE THREAD

**Issue by only-yao** [Gal4way/TPD#3]
Is there a convenient online testing page like gradio or streamlit for this great project?

**Comment by xdfeng07** [comment]
it is extremely easy to build one your self, you could refer to the gradio-demo code of OOTD, i build my own using OOTD's gradio code

**Comment by Nomination-NRB** [comment]
> it is extremely easy to build one your self, you could refer to the gradio-demo code of OOTD, i build my own using OOTD's gradio code

please show your code, otherwise shut up
