### ISSUE TITLE
Parallelism implementation for inference

### ISSUE THREAD

**Issue by KIRAN-MK-211** [Gal4way/TPD#9]
Hello authors, excellent work on Virtual Try on. Clearly, the best one I have seen. Congratulations! I was wondering how did you use multiple GPUs for inference. We have multiple GPUs and we wish to reduce the time of inference on our dataset. I tried a bunch of stuff like DataParallel, etc but maybe Im making a mistake. Can you please help in regards to which library is suitable for multi GPU inference of your model? Thanks in advance.

**Comment by Gal4way** [comment]
Hi there, I apologize for the delayed response as I have been busy with a new project recently. Regarding the multi-GPU parallelism in my code, you can refer to the CUDACallback function in main.py. This function is inherited from the Stable Diffusion codebase, and you can find more information in their repository.
